### ISSUE TITLE
Service Monitor Deployment Race condition

### ISSUE THREAD

**Issue by relyt0925** [openshift/ibm-roks-toolkit#91]
There's a race condition at cluster initialization with the manifest bootstrapper pod that will have it continuously fail and crash loop until the first worker is successfully provisioned in the cluster and the monitoring operator can roll out and initialize the `servicemonitors.monitoring.coreos.com` CRD. 

```
securitycontextconstraints.security.openshift.io            2020-10-24T00:01:18Z
servicecas.operator.openshift.io                            2020-10-24T00:01:38Z
servicemonitors.monitoring.coreos.com                       2020-10-24T00:15:27Z
```

You can see the creation of that corresponds to a couple minutes after the first worker node comes up in my cluster
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    projectcalico.org/IPv4Address: 10.93.34.24/26
    projectcalico.org/IPv4IPIPTunnelAddr: 172.30.32.192
  creationTimestamp: "2020-10-24T00:13:08Z"
```

Which then initializes the CRD and everything completes. This race condition that causes the manifest bootstrapper pod to CrashLoop until the servicemonitors CRD is initialized I believe can be removed if we either substantiate it with the manifest bootstrapper or rework the creation of it. 

It ultimately will complete on the first iteration when the openshift cluster has a node join in successfully and runs the `cluster-monitoring-operator-f7b47f45-kw7c4`

For more details here where the manifest is defined:
https://github.com/openshift/cluster-monitoring-operator/blob/170f91faabc9683a34df29d1d892027292ed0296/manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml 

There's two that I see get applied:
https://github.com/openshift/ibm-roks-toolkit/blob/master/assets/roks-metrics/roks-metrics-servicemonitor.yaml
https://github.com/openshift/ibm-roks-toolkit/blob/release-4.4/assets/cluster-bootstrap/cluster-kube-apiserver-servicemonitor.yaml

This also might be fine to accept but just thought I'd point it out.
